# Default values for helm_chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

web:
  replicaCount: 1
  image:
    repository: francescopalazzini/flasktest
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80

worker:
  replicaCount: 1
  image:
    repository: francescopalazzini/flasktest
    tag: latest
    pullPolicy: IfNotPresent

redis:
  replicaCount: 1
  image:
    repository: redis
    tag: 4-alpine
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 6379

ingress:
  enabled: false
