---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "helm_chart.fullname" . }}-worker
  labels:
    app: {{ template "helm_chart.name" . }}-worker
    chart: {{ template "helm_chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "helm_chart.name" . }}-worker
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "helm_chart.name" . }}-worker
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: REDIS_HOST
              value: {{ template "helm_chart.fullname" . }}-redis
          command: ["python"]
          args: ["worker.py"]
